#
#Program: Assign4
#Programmer : Itzel Fernandez
#ZID: z1850638
#
#
#Compiler variables
CCFLAGS = -Wall

#RULES TO LINK OBJECT CODE FILES TO CREATE EXECUTABLE FILES
Assign4: Assign4.cc
	g++ -Wall -g -std=c++11  Assign4.cc -o Assign4

clean:
	rm Assign4
