#
#Program : Assign3
#Programmer : ITZEL FERNANDEZ
#zID:  z1850638
#
#

# COmpiler Variables
CCFLAGS = -Wall

#Rule to link object code files to create executable file
Assign3: Assign3.cc
	g++ $(CCFLAGS) Assign3.cc -o Assign3

clean:
	rm Assign3
