#
#PROGRAM: Assignment5
#PROGRAMMER: Bhumika Niraula
#zID: z1832116
#

#Compiler Variables
CCFLAGS = -Wall

#Rule to compile source code files to object code
Assign5: Assign5.cc
	g++ -pthread -Wall -g -std=c++11 Assign5.cc -o Assign5

#Pseudo-target to remove object code and executable files
clean:
	-rm Assign5
